AWSTemplateFormatVersion: "2010-09-09"
Description: Kafka 4.2.0 + Conduktor Console on Amazon Linux 2023 (SSM AMI)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH KeyPair

  InstanceType:
    Type: String
    Default: t3.medium

Resources:

  KafkaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kafka and Conduktor access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9092
          ToPort: 9092
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  KafkaInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref KafkaSecurityGroup
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail

          dnf update -y
          dnf install -y java-17-amazon-corretto wget docker

          systemctl enable docker
          systemctl start docker

          # --- Install Kafka 4.2.0
          cd /opt
          wget https://dlcdn.apache.org/kafka/4.2.0/kafka_2.13-4.2.0.tgz
          tar -xzf kafka_2.13-4.2.0.tgz
          mv kafka_2.13-4.2.0 kafka

          mkdir -p /var/lib/kafka

          # --- Kafka KRaft configuration
          cat > /opt/kafka/config/server.properties <<EOF
          process.roles=broker,controller
          node.id=1
          controller.quorum.voters=1@localhost:9093
          listeners=PLAINTEXT://:9092,CONTROLLER://:9093
          inter.broker.listener.name=PLAINTEXT
          advertised.listeners=PLAINTEXT://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):9092
          controller.listener.names=CONTROLLER
          listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          log.dirs=/var/lib/kafka
          num.partitions=3
          offsets.topic.replication.factor=1
          transaction.state.log.replication.factor=1
          transaction.state.log.min.isr=1
          EOF

          /opt/kafka/bin/kafka-storage.sh format -t $(/opt/kafka/bin/kafka-storage.sh random-uuid) -c /opt/kafka/config/server.properties

          # --- systemd service
          cat > /etc/systemd/system/kafka.service <<EOF
          [Unit]
          Description=Apache Kafka
          After=network.target

          [Service]
          Type=simple
          ExecStart=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable kafka
          systemctl start kafka

          # --- Conduktor Console + Postgres via Docker
          docker network create conduktor-net || true

          docker rm -f conduktor-postgres || true
          docker run -d \
            --name conduktor-postgres \
            --network conduktor-net \
            -e POSTGRES_DB=conduktor \
            -e POSTGRES_USER=conduktor \
            -e POSTGRES_PASSWORD=conduktor \
            -p 5432:5432 \
            postgres:15

          docker rm -f conduktor-console || true
          docker run -d \
            --name conduktor-console \
            --network conduktor-net \
            -p 8080:8080 \
            -e CDK_DATABASE_URL="postgresql://conduktor:conduktor@conduktor-postgres:5432/conduktor" \
            conduktor/conduktor-console:latest

Outputs:
  PublicIP:
    Description: EC2 Public IP
    Value: !GetAtt KafkaInstance.PublicIp